site_name: TheHive4py Documentation

# mkdocs.yml
site_url: https://thehive-project.github.io/thehive4py
theme:
  name: "material"
  logo: 'images/thehive.png'
  palette:
    primary: 'blue'
    accent: blue

plugins:
  - search
  - awesome-pages:
        filename: .md  
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - thehive4py

extra_css:
  - custom.css

extra:
  social:
    - icon: fontawesome/solid/home
      link: "https://www.thehive-project.org"
    - icon: fontawesome/brands/wordpress
      link: "https://blog.thehive-project.org"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/TheHive_Project"
    - icon: fontawesome/brands/github
      link: "https://github.com/TheHive-Project"
    - icon: fontawesome/brands/gitter
      link: "https://gitter.im/TheHive-Project/TheHive"
repo_name: "TheHive-Project/TheHive4py"
repo_url: "https://github.com/TheHive-Project/TheHive4py"
markdown_extensions:
    - toc:
        permalink: "#"
    - codehilite
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed

